### ISSUE TITLE
Content: When and why to use a state management solution

### ISSUE THREAD

**Issue by pas2al** [angular-checklist/angular-checklist#18]
What about some hints about the usage of state management in general? NGRX seems to be overused in the community. Mike Ryan's talk is a very good one on this topic: https://youtu.be/omnwu_etHTY

Can we provide some "real" examples of when state management is a good fit and when it might be enough the handle state with a behaviour subject?

**Comment by d3lm** [comment]
Absolutely agreed. I'd consider this as a common pitfall and seen it in a couple of applications that people tend to overuse NGRX over other, already built-in tools like a `BehaviorSubject` + `scan` for state management even though it might not be needed in the first place.

Do you feel like working on this @pas2al?

Personally I'd love to have an item on this in the checklist.

What do you think @KwintenP?

**Comment by pas2al** [comment]
Yes, i can start working on it, but i would love to work with you two collaboratively on this one. I can create a first draft and then we start discussing on things to add or adapt?

**Comment by KwintenP** [comment]
Hi, 

I'm all for adding some real life examples to the checklist. 
I would propose to add them to already existing one in the category 'NGRX' called 'don't put everything in the store'. It already covers the SHARI principle.

Thanks for your input @pas2al!

**Comment by d3lm** [comment]
Agreed. Adding it to the existing one is a good idea.

**Comment by d3lm** [comment]
Any update on this one @pas2al?

**Comment by pas2al** [comment]
Not right now, i probably do it during the christmas days.

**Comment by d3lm** [comment]
Ok, thanks for the update. Have a wonderful Christmas time :santa: :christmas_tree:

**Comment by pas2al** [comment]
I made a small addition in #34
